version: "3.8"
services:
  db:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    restart: "always"
    volumes:
      - /opt/cti-stats-collector/clickhouse/data:/var/lib/clickhouse
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    container_name: db

  collector:
    build: ./packages/collector/
    depends_on:
      - db
    restart: "on-failure"
    volumes:
      - /opt/cti-stats-collector/cache:/opt/cti-stats-collector/cache
    environment:
      - DB_URL=db
      - CTI_FEEDS_FETCH_INTERVAL=${FEEDS_UPDATE_INTERVAL}
    container_name: collector

  storage:
    build: ./packages/storage
    depends_on:
      - db
    restart: "on-failure"
    environment:
      - DB_URL=db
    container_name: storage
